spring.application.name=sooqtalent
spring.datasource.url=jdbc:mysql://localhost:3306/sooqtalent?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
jwt.secret=1234567890123456789012345678901212345678901234567890123456789012
# CORS config and server port
server.port=8080